FROM openjdk:8-jdk-alpine

WORKDIR /home

COPY target/async-clientapp-0.0.1-SNAPSHOT-jar-with-dependencies.jar async-clientapp-jar-with-dependencies.jar

CMD ["java", "-jar", "async-clientapp-jar-with-dependencies.jar"]