version: '3.3'
services:
  clientapp:
    build: ./async-clientapp
    container_name: clientapp
    networks:
      - my_net
    depends_on:
      - sender-pull
  serverapp:
    build: ./async-serverapp
    container_name: serverapp
    networks:
      - my_net
  sender-pull:
    build: ./async-sender-pull
    container_name: sender-pull
    networks:
      - my_net
    depends_on:
      - receiver-pull
  receiver-pull:
    build: ./async-receiver-pull
    container_name: receiver-pull
    networks:
      - my_net
    depends_on:
      - serverapp
networks:
  my_net:
    driver: bridge